### PR TITLE
Expedition Corps Upgrate

### PR DESCRIPTION
**Pull request by masline147**
## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by FeenieRU** [comment]
upgra_**d**_e 🤓

**Comment by masline147** [comment]
Это мой репозторий, я просто эксперементирую

**Comment by masline147** [comment]
А... я не туда его запилил

**Comment by masline147** [comment]
Щас уберу

**Comment by RaShCat** [comment]
Хах...

**Pull request closed without merging**
